name: check

on: [pull_request]

jobs:
  check:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup check
      run:  scripts/setup_check.sh

    - name: Check
      run:  scripts/check.sh --test-only
